name: Lint
on: 
  push:
      branches:
          - 'master'
      paths-ignore:
        -'./README.md'
        -'./tricks.yaml'
        -'documentation/**'
        -'logs/**'
    
    pull_request:
      paths-ignore:
        -'./README.md'
        -'./tricks.yaml'
        -'documentation/**'
        -'logs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --color"