name: Continuous Integration
on: 
  push:
    paths-ignore:
      -'./README.md'
      -'./tricks.yaml'
      -'documentation/**'
      -'logs/**'
  
  pull_request:
    paths-ignore:
      -'./README.md'
      -'./tricks.yaml'
      -'documentation/**'
      -'logs/**'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # only output hash of image and pass that to docker run
      - run: docker run --rm $(docker build -q . --target testing)

  slackNotification:
    name: Slack notification
    runs-on: ubuntu-latest
    environment: Build and Test environment
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification Build & Test
      uses: bryannice/gitactions-slack-notification@2.0.0
      env:
        SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'Build and test workflow running'
        SLACK_TITLE: 'Build and Test Notification'