name: Workflow Notification
on:
  # note workflow_run only triggers if workflow file is on the default branch!
  workflow_run:
    workflows: ["Continuous Integration"]
    types: 
      - completed

jobs:
  notify:
    name: Notify
    needs: 
    on-success:
      environment: Build and Test environment
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - uses: actions/checkout@v2
        - name: Slack Notification Workflow Passed
          uses: bryannice/gitactions-slack-notification@2.0.0
          env:
            SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: 'Build and Test Workflow Success!'
            SLACK_TITLE: 'SUCCESS - Build and Test Success!'
  
  notifyOnFailure:
    name: NotifyFailure
    on-failure:
      environment: Build and Test environment
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - uses: actions/checkout@v2
        - name: Slack Notification Build & Test
          uses: bryannice/gitactions-slack-notification@2.0.0
          env:
            SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: 'Build and Test Workflow Failed!'
            SLACK_TITLE: 'FAILURE - Build and Test Workflow Failed'